### ISSUE TITLE
Create my own wakatime stats widget

### ISSUE THREAD

**Issue by worthant** [worthant/worthant#2]
## Requirements

1. High availability, near instant updates
2. Cool graphs using matplotlib, ds using pandas, jupyter notebook for showcase
3. Practise python, for fun, don't use gpt too much - learn more for CV
4. (optional) Then potentially rewrite in Rust, for fun
5. (optional) Create smart contract, make this widget payable through it (TON/Solana blockchain)

## TODO

- [ ] Divide into smaller tasks on kanban board
- [x] Choose tech stack & deployment platform
- [ ] Write MVP with simple request to wakatime REST API & make working deploy

**Comment by worthant** [comment]
## Tech stack

Lang: Python
Framework: Flask 3
Data visualization library: matplotlib
Db: SQLite (for caching in the future)
Hosting: Vercel serverless functions
Automation: github actions, as usual
Name: `awesome-wakatime-stats`
